### ISSUE TITLE
Bug: file out of source directory

### ISSUE THREAD

**Issue by FDiskas** [remoteinterview/zero#38]
If my file structure like this:
```
- components
-- some-component.js
- src
-- index.js
```
And I import `../components/some-component.js` component in `index.js` it will fail after i run `zero src`

Why I want todo like so? I just don't want that `zero` build an route like `components` and thous components would be available only frontend.

**Comment by FDiskas** [comment]
The main reason why this is not working that `zero` builds only all files within current directory and the target is somewhere in system `tmp` directory. :poultry_leg:

**Comment by FDiskas** [comment]
Discussion: https://spectrum.chat/zero/general/alias-nested-directory~02e8660b-6a3e-4424-9094-a256804e232f :panda_face:

**Comment by asadm** [comment]
You are right. `zero` copies the files to `tmp` directory because it modifies and add `node_modules` etc. to make things work. When you run `zero src`, it only copies `src` to the tmp. For now, any folder/file that starts with _ (underscore) is not exposed. So you can have `_components` inside `src` to achieve the same effect.

I think the right way to solve this issue would be [`.zeroignore` file](https://github.com/remoteinterview/zero/issues/25). This feature is yet to land but should be finalized this week. Then you can have `components` inside `src` without exposing them.

**Comment by chimon2000** [comment]
What if I had two directories (**api** and **web**)  and I wanted one of them to be served as the root (in this case web).  It seems like there should be a way to configure this as I could see this being a very common scenario.

**Comment by FDiskas** [comment]
One solution would be create two directories like so:
```
web
-- package.json
api
-- package.json
package.json
```
[zero-server_1552838463558.zip](https://github.com/remoteinterview/zero/files/2975385/zero-server_1552838463558.zip)
But for me looks like a hack. Any suggestions? :speedboat:
Also getInitialProps() method will be missed in this case and no SSR.

**Comment by asadm** [comment]
Importing files from out of web directory should work now in v1.1.
