### ISSUE TITLE
Bump TypeScript version to latest

### ISSUE THREAD

**Issue by asadm** [remoteinterview/zero#82]
Zero is using a bit older version of TypeScript. We need to update it to latest version. Off the top of my head:

- [ ] [Clone, install and run zero locally](https://github.com/remoteinterview/zero/blob/master/CONTRIBUTING.md#contributing-to-zero).
- [ ] Update in packages [here](https://github.com/remoteinterview/zero/blob/master/packages/common-deps/package.json), [here](https://github.com/remoteinterview/zero/blob/master/packages/dep-tree-js/package.json).
- [ ] Run tests (`npm run test`) and see if all of them pass.
- [ ] Send PR :)

**Comment by CmdEngineer** [comment]
I can take this one

**Comment by asadm** [comment]
Give it a shot if you want, we can always (try to) resolve conflicts 😄

**Comment by CmdEngineer** [comment]
I received this after testing an unedited version of Zero:
Test Suites: 2 failed, 8 passed, 10 total
Tests:       13 failed, 48 passed, 61 total
Snapshots:   0 total
Time:        1079.525s
Ran all test suites.

After upgrading typescript to 3.6.4 (latest): [Test pasted](https://pastebin.com/FmhUtU0t)
Typescript seems to work (the new version) however other libraries for me fail the test, which doesn't seem to be because of the change just because of my computer.

**Comment by asadm** [comment]
Interesting, what OS/version are you on?

I would say still make the PR, our CI will run it against all platforms anyway.

**Comment by CmdEngineer** [comment]
I am on Windows 10. I will PR it then thank you, please don't mark it as spam then I would highly appreciate it.
